[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "mnist_nn"
version = "0.1.0"
authors = [
  { name="CheesyChocolate", email="example@example.com" },
]
description = "Neural networks for MNIST pattern recognition"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "numpy>=1.24.0",
    "scipy>=1.10.0",
    "matplotlib>=3.7.0",
    "scikit-learn>=1.2.0",
    "pandas>=2.0.0",
    "torch>=2.0.0",
    "tensorflow>=2.11.1",
    "seaborn>=0.13.2",
]

[project.urls]
"Homepage" = "https://github.com/cheesychocolate/mnist_nn"
"Bug Tracker" = "https://github.com/cheesychocolate/mnist_nn/issues"

[tool.hatch.build.targets.wheel]
packages = ["src"]

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.envs.default]
dependencies = [
  "pytest",
  "pytest-cov",
]
[tool.hatch.envs.default.scripts]
cov = "pytest --cov-report=term-missing --cov-config=pyproject.toml --cov=src --cov=tests {args}"
no-cov = "cov --no-cov {args}"

[[tool.hatch.envs.test.matrix]]
python = ["38", "39", "310", "311"]

[tool.coverage.run]
branch = true
parallel = true
omit = [
  "src/__about__.py",
]

[tool.coverage.report]
exclude_lines = [
  "no cov",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
]
